// lib/mock-data.ts
// This file contains mock data for products, users, and orders.

import { Product, User, Order } from './types';

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Camiseta 'Big Dreams'",
    description: "Una camiseta de algodón suave con un diseño gráfico inspirador. Perfecta para el día a día.",
    price: 85000,
    imageUrl: "/products/camisetas/big-dreams-tshirt.png",
    category: "camisetas",
    rating: 4.5,
    reviews: 120,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Negro", "Blanco", "Rojo"],
    stock: 50,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Hoodie 'Urban Explorer'",
    description: "Hoodie oversized con capucha y bolsillo canguro. Ideal para un look urbano y relajado.",
    price: 150000,
    imageUrl: "/placeholder.svg?height=400&width=400",
    category: "hoodies",
    rating: 4.8,
    reviews: 85,
    sizes: ["M", "L", "XL"],
    colors: ["Gris Oscuro", "Gris"],
    stock: 30,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Pantalón Cargo 'Street Vibe'",
    description: "Pantalón cargo resistente con múltiples bolsillos, diseñado para la comodidad y el estilo en la calle.",
    price: 120000,
    imageUrl: "/placeholder.svg?height=400&width=400",
    category: "pantalones",
    rating: 4.2,
    reviews: 60,
    sizes: ["S", "M", "L"],
    colors: ["Carbón", "Negro"],
    stock: 25,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Camiseta 'Oversized Tee'",
    description: "Camiseta de corte amplio para máxima comodidad y un estilo moderno. Disponible en varios colores.",
    price: 70000,
    imageUrl: "/products/camisetas/oversized-tee.png",
    category: "camisetas",
    rating: 4.6,
    reviews: 95,
    sizes: ["M", "L", "XL"],
    colors: ["Blanco", "Negro", "Azul"],
    stock: 40,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Gorra '717 Logo'",
    description: "Gorra clásica con el logo bordado de 717 Store. Un accesorio esencial para tu outfit.",
    price: 45000,
    imageUrl: "/placeholder.svg?height=400&width=400",
    category: "accesorios",
    rating: 4.7,
    reviews: 200,
    sizes: ["Única"],
    colors: ["Negro", "Rojo", "Blanco"],
    stock: 60,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Camiseta 'Graphic Tee Blood'",
    description: "Camiseta con un diseño gráfico audaz y vibrante. Hecha para destacar.",
    price: 90000,
    imageUrl: "/products/camisetas/graphic-tee-blood.png",
    category: "camisetas",
    rating: 4.4,
    reviews: 70,
    sizes: ["S", "M", "L"],
    colors: ["Negro", "Rojo"],
    stock: 35,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "7",
    name: "Camiseta 'Graphic Tee Pain'",
    description: "Diseño único que expresa la lucha y la superación. Confeccionada para durar.",
    price: 90000,
    imageUrl: "/products/camisetas/graphic-tee-pain.png",
    category: "camisetas",
    rating: 4.3,
    reviews: 55,
    sizes: ["M", "L", "XL"],
    colors: ["Blanco", "Negro"],
    stock: 30,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "8",
    name: "Chaqueta 'Windbreaker'",
    description: "Chaqueta cortavientos ligera y estilosa, ideal para cualquier clima urbano.",
    price: 180000,
    imageUrl: "/placeholder.svg?height=400&width=400",
    category: "chaquetas",
    rating: 4.9,
    reviews: 40,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Negro", "Verde", "Azul"],
    stock: 20,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockUsers: User[] = [
  {
    id: "user1",
    name: "Juan Perez",
    email: "juan.perez@example.com",
    passwordHash: "hashedpassword123", // In a real app, this would be a strong hash
    createdAt: new Date("2023-01-15T10:00:00Z").toISOString(),
    lastLogin: new Date("2024-07-20T14:30:00Z").toISOString(),
    orderCount: 3,
    totalSpent: 450000,
    isActive: true,
    phone: "3001234567",
    role: "user",
    shippingAddresses: [
      {
        id: 'addr1',
        userId: 'user1',
        fullName: 'Juan Pérez',
        address1: 'Calle 123 #45-67',
        address2: 'Apto 101',
        city: 'Bogotá',
        state: 'Cundinamarca',
        zipCode: '110111',
        country: 'Colombia',
        isDefault: true,
      },
    ],
  },
  {
    id: "admin1",
    name: "Admin User",
    email: process.env.NEXT_PUBLIC_ADMIN_EMAIL || "admin@717store.com",
    passwordHash: "adminpassword", // In a real app, this would be a strong hash
    createdAt: new Date("2022-05-01T08:00:00Z").toISOString(),
    lastLogin: new Date("2024-07-26T09:00:00Z").toISOString(),
    orderCount: 10,
    totalSpent: 1200000,
    isActive: true,
    phone: "3201112233",
    role: "admin",
    shippingAddresses: [],
  },
];

export const mockOrders: Order[] = [
  {
    id: "ORD001",
    userId: "user1",
    createdAt: "2024-07-20T10:00:00Z",
    updatedAt: "2024-07-20T10:00:00Z",
    status: "Entregado",
    total: 235000,
    items: [
      { productId: "1", name: "Camiseta 'Big Dreams'", quantity: 1, price: 85000, imageUrl: "/products/camisetas/big-dreams-tshirt.png", size: "M", color: "Negro" },
      { productId: "5", name: "Gorra '717 Logo'", quantity: 1, price: 45000, imageUrl: "/placeholder.svg?height=400&width=400", size: "Única", color: "Rojo" },
      { productId: "4", name: "Camiseta 'Oversized Tee'", quantity: 1, price: 70000, imageUrl: "/products/camisetas/oversized-tee.png", size: "L", color: "Blanco" },
    ],
    shippingAddress: {
      fullName: "Juan Perez",
      address1: "Calle 10 #20-30",
      city: "Bogotá",
      state: "Cundinamarca",
      zipCode: "110111",
      country: "Colombia",
    },
    paymentMethod: "Tarjeta de Crédito",
  },
  {
    id: "ORD002",
    userId: "user2", // Assuming user2 exists or will be created
    createdAt: "2024-07-22T14:30:00Z",
    updatedAt: "2024-07-22T14:30:00Z",
    status: "Pendiente",
    total: 150000,
    items: [
      { productId: "2", name: "Hoodie 'Urban Explorer'", quantity: 1, price: 150000, imageUrl: "/placeholder.svg?height=400&width=400", size: "L", color: "Gris Oscuro" },
    ],
    shippingAddress: {
      fullName: "Maria Garcia",
      address1: "Carrera 50 #15-25",
      city: "Medellín",
      state: "Antioquia",
      zipCode: "050001",
      country: "Colombia",
    },
    paymentMethod: "PayPal",
  },
  {
    id: "ORD003",
    userId: "user1",
    createdAt: "2024-07-25T09:15:00Z",
    updatedAt: "2024-07-25T09:15:00Z",
    status: "Enviado",
    total: 90000,
    items: [
      { productId: "6", name: "Camiseta 'Graphic Tee Blood'", quantity: 1, price: 90000, imageUrl: "/products/camisetas/graphic-tee-blood.png", size: "S", color: "Rojo" },
    ],
    shippingAddress: {
      fullName: "Juan Perez",
      address1: "Calle 10 #20-30",
      city: "Bogotá",
      state: "Cundinamarca",
      zipCode: "110111",
      country: "Colombia",
    },
    paymentMethod: "PSE",
  },
];
